version: "3.8"
services:
  back-end:
    container_name: caderneta-backend
    build:
      context: ./BackEnd-Caderneta
      dockerfile: Dockerfile
    networks:
      - caderneta-network
    ports:
      - "8080:8080"

  front-end:
    container_name: caderneta-frontend
    build:
      context: ./FrontEnd-Caderneta
      dockerfile: Dockerfile
    networks:
      - caderneta-network
    ports:
      - "80:80"
      - "443:443"

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"

networks:
  caderneta-network:
    name: caderneta-network
    driver: bridge
